config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root 'photos#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
      if params[:search]
        @photos = Photo.search(params[:search]).order("created_at DESC")
      else
        @photos = Photo.all.order('created_at DESC')
      end
    end
  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :description, :url, :photo_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Station</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <!-- <div class="field">
    <%= f.label :photo_id %><br>
    <%= f.number_field :photo_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="webcontainer">
    <h1>Stationgram</h1>
    <%= button_to 'Upload a picture', new_photo_path, :method => "get" %>
</div>
<hr>

<!-- <%= form_tag(photos_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Pictures" %>
<%= submit_tag "Search" %> -->
<% end %>

<br>
<body>
<div>
<ul>
    <% @photos.each do |photo| %>
        <li>
            <strong> Caption: <%= photo.title %> </strong><br>
            <%= link_to image_tag(photo.url,:size => "500x500"), photo %><br>
            <!-- <%= link_to 'Edit', edit_photo_path(photo) %> | -->
            <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
        <br>
    <% end %>
</ul>
</div>
</body>

  <div class="footer">
    &copy; Arvin Hadisurya
  </div>

<br>

app/views/photos/new.html.erb
<h1>New Photo</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<div class="webcontainer">
<h1>SMILEEE</h1>
<%= button_to 'Upload a picture', new_photo_path, :method => "get" %>
<hr>
<p id="notice"><%= notice %></p>
<br>

<!-- <%= link_to 'Edit', edit_photo_path(@photo) %> --> |
<%= link_to 'Back', photos_path, :class => 'back' %> |

<p>
  <strong>Name:</strong>
  <%= @photo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<p>
  <%= image_tag @photo.url, :size => "800x800" %>
</p>




<div class="footer">
  &copy; Arvin Hadisurya
</div>


<div>